accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views 
from .views import SignUpView

urlpatterns = [
    #path('', views.login, name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

contactus/urls.py
from django.urls import path
from . import views
from django.conf.urls import include

app_name = 'contactus'

urlpatterns = [
    path("", views.contactusform, name='contactus')
]

homepage/urls.py
from django.urls import path, include
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.homepage, name="home"),
]

planproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('accounts.urls')),
    path('accounts/', include('accounts.urls')), #signup
    path('accounts/', include('django.contrib.auth.urls'), name='login'), #login 
    path('contact/', include('contactus.urls'),name='contactus'), #contact us
    path('', include('homepage.urls')),
    path('todolist/', include('todolist.urls')), #todolist
    path('schedule/', include('schedule.urls')), #schedule
]

schedule/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

urlpatterns = [
    path('schedule-exists/', views.validate_class, name='validate_class'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('', views.schedule, name='schedule'),
]

todolist/urls.py
from django.urls import path, include
from . import views

app_name = 'todolist'
urlpatterns = [
    path('', views.plan, name="plan"),
    path('delete/<id>', views.delete_plan, name="delete_plan"),
]

accounts/models.py
from django.db import models

# Create your models here.

contactus/models.py
from django.db import models

class Contactus(models.Model):
    contactus = models.CharField(max_length=150,default='')
# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# from accounts import models

class ScheduleModels(models.Model):

    # userlink = models.OneToOneField(User, on_delete=models.CASCADE, default=None)

    day         = models.CharField(max_length = 50)
    kelas       = models.CharField(max_length = 50)
    period      = models.CharField(max_length = 50)
    time        = models.CharField(max_length = 50)
    lecturer    = models.CharField(max_length = 50)
    
    def __str__(self):
        return "{}. {}".format(self.id, self.kelas)

todolist/models.py
from django.db import models

# Create your models here.
class ToDoList(models.Model):
    Plan = models.CharField(max_length=50)
    Date = models.DateField(max_length = 10, default="Unknown")

    def __str__(self):
        return "{}{}".format(self.Plan, self.Date)

contactus/forms.py
from django.forms import ModelForm
from .models import Contactus
from django import forms

class contactusForm(ModelForm):
    contactus = forms.CharField(widget=forms.Textarea, label='')
    class Meta:
        model = Contactus
        fields = ['contactus']

schedule/forms.py
from django import forms
from .models import ScheduleModels

class ScheduleForms(forms.ModelForm):
    class Meta:
        model = ScheduleModels
        fields = [
            'day',
            'kelas',
            'period',
            'time',
            'lecturer',
        ]

todolist/forms.py
from django import forms
from .models import ToDoList

class PlannerForm(forms.ModelForm):
    class Meta:
        model = ToDoList
        fields = ['Plan']

        widgets = {
            'Plan':forms.TextInput(attrs={'class': 'form-control'}),
        }

accounts/views.py
from django.shortcuts import render

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

contactus/views.py
from django.shortcuts import render
from .forms import contactusForm
from .models import Contactus
from django.shortcuts import redirect

def contactusform(request):
    if request.user.is_authenticated:
        form = contactusForm(request.POST)
        if form.is_valid():
            form.save()

        formcontact = contactusForm()
        contact1 = Contactus.objects.all()
        context = {
            'list_form':contact1 ,
            'formcontact':formcontact
        }
        return render(request,'contactus.html',context)

    else:
        return render(request, 'notlogged.html')

# Create your views here.

homepage/views.py
from django.shortcuts import render
from django.contrib.auth.models import User,auth
from todolist.models import ToDoList

# Create your views here.
def homepage(request):
    context = {}
    if request.user.is_authenticated:
        obj = ToDoList.objects.all()
        context = {
            'obj':obj
        }
        return render(request, 'home.html', context)
        
    else:
        return render(request, 'notlogged.html')

schedule/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from .models import ScheduleModels
from .forms import ScheduleForms
from django.views.generic.edit import View
import json


# Create your views here.

def schedule(request):

    # if request.user.is_authenticated:
    schedule_model = ScheduleModels.objects.all()
    # schedule_model = ScheduleModels.objects.get(userlink=request.user)
    schedule_form = ScheduleForms(request.POST or None)
    monday_schedule = []
    tuesday_schedule = []
    wednesday_schedule = []
    thursday_schedule = []
    friday_schedule = []
    saturday_schedule = []
    sunday_schedule = []
    error = None

    if request.method =='POST':
        if schedule_form.is_valid():
            schedule_form.save()

    for schedule in schedule_model:
        if schedule.day == "Monday":
            monday_schedule = [schedule]

        elif schedule.day == "Tuesday":
            tuesday_schedule = [schedule]
        
        elif schedule.day == "Wednesday":
            wednesday_schedule = [schedule]
        
        elif schedule.day == "Thursday":
            thursday_schedule = [schedule]

        elif schedule.day == "Friday":
            friday_schedule = [schedule]

        elif schedule.day == "Saturday":
            saturday_schedule = [schedule]

        elif schedule.day == "Sunday":
            sunday_schedule = [schedule]


    context = {
        'schedule_form':schedule_form,
        'schedule_model':schedule_model,
        'monday_schedule':monday_schedule,
        'tuesday_schedule':tuesday_schedule,
        'wednesday_schedule':wednesday_schedule,
        'thursday_schedule':thursday_schedule,
        'friday_schedule':friday_schedule,
        'saturday_schedule':saturday_schedule,
        'sunday_schedule':sunday_schedule,
    }

    if request.user.is_authenticated:
        return render(request, 'schedule.html', context)

    else:
        return HttpResponseRedirect('/')

def delete(request, delete_id):
    ScheduleModels.objects.filter(id=delete_id).delete()

    return HttpResponseRedirect('/schedule/')


def validate_class(request):
    cek_kelas = request.GET['kelas']

    schedule = ScheduleModels.objects.all()

    for sched in schedule:
        if sched.kelas == cek_kelas:
            data = {
                'is_exists':True
            }
    
    return JsonResponse(data)

todolist/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from .models import ToDoList
from .forms import PlannerForm

# Create your views here.
def plan(request):
    if request.user.is_authenticated:
        form = PlannerForm()
        plans = {'form':form, 'all_plans':ToDoList.objects.all().order_by('Date')}
        if request.method == 'POST':
            planform = PlannerForm(request.POST)
            plan = planform.data['Plan']
            date = request.POST.get('date')
            hasil = ToDoList(Plan=plan, Date=date)
            hasil.save()

        return render(request, 'planner/todolist.html', plans)

    else:
        return HttpResponseRedirect('/')

def delete_plan(request, id):
    target_delete = ToDoList.objects.get(id=id)
    target_delete.delete()
    return redirect('todolist:plan')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Let's Plan</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <script src="https://kit.fontawesome.com/a222d351e0.js" crossorigin="anonymous"></script>
  {% block title %}
  {% endblock %}
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark">
      <div class="container-fluid">
          <a class="navbar-brand logo" href="#">
            <h2>LETS'S PLAN</h2>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="nav navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link active" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:plan' %}">Planner</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/schedule/">Schedule</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contactus:contactus' %}">Contact Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
              </li>
            </ul>
          </div>
      </div>
      </nav>
      
      <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  {% block content %}

  {% endblock %}
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</html>

templates/contactus.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/contactus.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a222d351e0.js" crossorigin="anonymous"></script>
    <title>Document</title>
  {% endblock %}
</head>

<body>
  {% block content %}
  {% if user.is_authenticated %}
  <div class="flex-item-right">
    <h1>Do you have any</h1>
    <h1>recommendations? </h1>
    <form class="container" style="font-size: 20px;"method="POST">
      {% csrf_token %}
      {{formcontact | crispy}}       
      <div class="btn-1">
        <button type="submit" class="btn">Submit</button>
      </div>
    </form><br>
    <div class="containerr">
    {% if list_form %}
      {% for contact1 in list_form %}
      {{ user.username }} - {{ contact1.contactus }} <br>
      {% endfor %}
    {% endif %}
    </div>
    {% else %}
    <a href="{% url 'homepage:home' %}"></a>

  {% endif %}
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/contactus.js' %}"></script>
  {% endblock content %}
</body>
  
  
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
  {% endblock %}
</head>
<body>
  {% block content %}
  {% if user.is_authenticated %}
    <div class="flex-container" id="container">
        <img id="image" src="{% static 'img/undraw_To_do_list_re_9nt7.svg' %}">
        <div class="flexcontainer-text">
            <p id="judul">Hi, {{ user.username }}!</p>
        </div>
    </div>

    <div class="yourtask-container">
        <h5 id="task">Your Task</h5>
    </div>   
    <div class="container space">
        {% for i in obj %}
        <div class="empty"></div>
        <div class="row">
             <div class="col-1 number center">{{ forloop.counter }}</div>
            
             <div class="col-11 content">
                <div class="d-flex">
                    <div class="d-flex flex-column center">
                        <h5>Plan : {{ i.Plan}}</h5>
                        <h5>Date : {{ i.Date }}</h5>
                    </div>
                </div> 
            </div>
        </div>
        {% endfor %}
            
    </div>


  {% else %}
    <a href="{% url 'homepage:home' %}"></a>

{% endif %}
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
    $(document).ready(function(){
      $("#judul").hover(function(){
            $(this).text("Ready to start your day with your planner ?");
            
        }, function() {
            $(this).text("Hi, {{ user.username }}!");
        });
      $("#image").click(function(){
        $("#image").fadeOut();
      });
      $("#task").on("click", function(){
        $(this).hide();
      });
    });
  </script>
</body>

{% endblock %}
</html>

templates/notlogged.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>notlogged</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/notlogged.css' %}">
    {% endblock %}
</head>
<body>
{% block content %}
    <div class="container content">
        <div class="row image">
            <img src="{% static 'img/undraw_oops_notloggedin.svg' %}">
        </div>
        <div class="row text-logout">
            <h1>Oops... you’re not logged in</h1>
        </div>
        <div class="in">
            <a href="{% url 'login' %}"><button class="btn log">Log In</button></a>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/planner/todolist.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    {% block title %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a222d351e0.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/todolist.css' %}">
    {% endblock %}
</head>

<body>
    {% block content %}
    <!-- Trigger the modal with a button -->
    <div class="flex-container">
        <button type="button" class="btn" data-toggle="modal" data-target="#myModal">Add a plan</button>
    </div>

    <!-- Modal -->
    <form method="POST" id="myForm">
        {% csrf_token %}
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content form-content">
                    <div class="modal-header">
                        <h4 class="modal-title">What to Do?</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <div class="modal-body">
                        {% for field in form %}
                            {{ field.label_tag }}
                            {{ field }}
                            <div class="empty"></div>
                            <label for="fdate">Date (YYYY-MM-DD):</label>
                            <input name="date" id="fdate" type="date" required>
                        {% endfor %}  
                    </div>
                    <br>
                    <div class="modal-footer">
                        <button type="submit" class="btn">Save</button>
                    </div>
            
                </div>
            </div>
        </div>
    </form>
    <!-- </div> -->

    <div class="container space">
        {% for plan in all_plans %}
        <div class="row empty"></div>
        <div class="row">
             <div class="col-1 number center">{{ forloop.counter }}</div>
            
             <div class="col-11 content">
                <div class="d-flex">
                    <div class="d-flex flex-column center">
                        <h5>Plan : {{ plan.Plan}}</h5>
                        <h5>Date : {{ plan.Date }}</h5>
                    </div>
                    <div class="d-flex delete">
                        <a class="btn-2" href="{% url 'todolist:delete_plan' id=plan.id %}" role="button">Delete</a>
                    </div>
                    
                </div> 
            </div>
        </div>
        {% endfor %}
            
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/todolist.js' %}"></script>
    {% endblock content %}
</body>
</html>